namespace AnimeBird.Parser.Elements
{
    internal enum ElementCategory
    {
        AnimeSeason,
        AnimeSeasonPrefix,
        AnimeTitle,
        AnimeType,
        AnimeYear,
        AudioTerm,
        DeviceCompatibility,
        EpisodeNumber,
        EpisodeNumberAlt,
        EpisodePrefix,
        EpisodeTitle,
        FileChecksum,
        FileExtension,
        FileName,
        Language,
        Other,
        ReleaseGroup,
        ReleaseInformation,
        ReleaseVersion,
        Source,
        Subtitles,
        VideoResolution,
        VideoTerm,
        VolumeNumber,
        VolumePrefix,
        Unknown
    }
}
